language: ruby

branches:
  only:
    - master

sudo: required

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

services:
  - docker

env:
  - SUITE=unit
  - SUITE=sensu-latest
  - SUITE=sensu-029

script:
  - if test "$SUITE" = "unit"; then bundle exec rake; fi
  - if test "$SUITE" != "unit"; then chef exec kitchen test $SUITE; fi

stages:
  - name: test
  - name: deploy
    if: NOT type = cron AND branch = master

jobs:
  include:
    - stage: deploy
      install: skip
      env:
        - VERSION=`ruby -e 'print Gem::Specification.load("sensu-plugins-meta.gemspec").version'`
      script: skip
      before_deploy:
        - openssl aes-256-cbc -K $encrypted_f809c79576c5_key -iv $encrypted_f809c79576c5_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
        - chmod 0600 ~/.ssh/id_rsa
        - git remote set-url origin git@github.com:socrata-platform/sensu-plugins-meta
        - git tag -a v${VERSION} -m "Tagging v${VERSION} for release"
        - git push --tags
      deploy:
        provider: rubygems
        api_key:
          secure: FFC8P5cFbzjngxhbZqSU3qjCEsj86Tlpn34LMUUlaf5vTEeFdhzsGjHmo7cJA7DvBdBPuDDJTqKxbR6WNjek55VeA48dG+diVBG1bS9VhQ0VdpuZHBhFU1PdteizK4tefCiK7f89CjsL1sV8+mHCMzdjO0QlxHNqJPAx7vmeFdadNKTfWia4+9XampH5d7JzdA0LgdJyci01A+o68R5ZCRJ+q7cxVWlW8dZcjMrThVfwAZSwgjoK8E3nSoxcJxqXTaoQBp3DDRpoNx8PrAc58umCDIc+twKyPtkRMVIxfzoYS38LabQ2eIgna8E9rZS7x+YkWJI0y9pz0ffRy1tvHWVhtixvQeiMjnghiGTlFiqvjS2VFC37JngFSLtoeNrIqxjpu+jCmWsJbCxzYSBvtOnWwfpQqhl2MdkRC7QqlQsTJZrOydfEmX6dC04aYZJvjbctrPvRb81wlwOEiY+orl0E8gyvIDxL6hpJRlkcIkIzYVLj0UBI87fEkN6/Sr+jbJBzn4Rf55H9+p+3XFBmSnv4mmEJ/tDu0U1gnrMPvfTbm5Ob5xtvx4HuIH9gWYcgoutEYqqkF5PYeaD/MwN7d2MZFbHMq9N+F5Egy5p+175CHKBWUkgHgU0OB6RpLfjYP01u5Nql6vJjA5jzMHEz+PVCGFSYrxbcwQbCi0ODSvk=

notifications:
  slack:
    on_failure: change
    on_success: never
    on_pull_requests: false
    rooms:
      - secure: A5g8uL03wyzNET2T5XtB2rJrEdzQQfnJITtyGGD64KzjOwbP0p6YBxbo08M6CQl3PLDzxGRLlz4WGamSG9XrZ9cPRozjohpdlosXtOSAvOvbULWWr2QYs2KZjrcEdUxytw6noqbMyE9zATcIY8Cmj6J4YPRJE1wag7q45M5H3L7Ya7mXwcBSu2hsuLPIgaUVst3eKsT5j4Zt7xLjFRnuAjZMdvS4RanYkEqfkGo4xswAw3uNbYrieUABBoAjCYg0Fx/b4yn3VO+xO3WaTbiYHmsEBDzpwFCpukK5tgCQj0bGlobhJfAIfKm7A0E8t6swIoQ+yLJ5XO7cRaoq2jRgdQ+uXok2OoU2CYOouZCE7mTZ/qHl38/VmEhVr/AkLx2A4CbtHrhkWvSsA1F7A6AuhjnsYmWf4M7e3G/ECTUi0DWXAUDKlS606FS4t4dqlYhFitVPuNjx/YmT8r5++NsptXIebXqUCk3M+eeHuUEtI8NugX1rb08TWvSxzdwNX5GG2fCiZz7GHN+91zTOVd/bTyRFh4GA7xVGm0I2/7ZsJBfzBL5Dr1xl7jISq9BCohxRTdsd8DZBoCn+8O3wBNVbHK7CJwNJu8qgJEAJ/OIO4guBDi/Y/4Z6EJfENbwHcZNJ+c+J4WChTiBQBLS5grYodmJMShYNRgA1AOST+vW2FaY=
